CREATE TABLE IF NOT EXISTS user
(
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    image       TEXT,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status      TINYINT      NOT NULL REFERENCES user
);

CREATE TABLE IF NOT EXISTS user_status
(
    id   TINYINT         NOT NULL PRIMARY KEY,
    text VARCHAR(50) NOT NULL
);